#!/usr/bin/env bash
# transfers file from local to other computer

if [ $# -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit
fi

LOCAL_FILE=$1
IP=$2
USERNAME=$3
KEY=$4

if [ "$KEY" ]; then
	scp -i "$KEY" "$LOCAL_FILE" "$USERNAME@$IP:~/"
else
	scp "$LOCAL_FILE" "$USERNAME@$IP:~/"
fi
