#!/usr/bin/env bash
#installs nginx with root returning "Holberton School"

sudo apt-get update
sudo apt-get install -y nginx

sudo sh -c 'echo "Holberton School for the win!" > /usr/share/nginx/html/index.html'

sudo service nginx restart
