#!/usr/bin/env bash
#installs nginx with root returning "Holberton School"

sudo apt-get update
sudo apt-get install -y nginx

sudo cp config /etc/nginx/sites-available/default
sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

sudo service nginx reload && sudo service nginx restart
