#!/usr/bin/env bash
#installs nginx with root returning "Holberton School"

sudo apt-get update
sudo apt-get install -y nginx

wget https://raw.githubusercontent.com/glyif/holberton-system_engineering-devops/master/0x09-web_server/config
sudo cp config /etc/nginx/sites-available/default
sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html

sudo service nginx reload && sudo service nginx restart
