#!/usr/bin/env bash
# run nginx as nginx
wget  -O /etc/nginx/nginx.conf
wget  -O /etc/nginx/sites-available/default
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo chown -R nginx /var/log/nginx /etc/nginx /usr/share/nginx
sudo chmod u+x /etc/nginx/nginx.conf
pkill -9 apache2
su nginx -c nginx
